In [2]:
import pandas as pd

In [6]:
df = pd.read_csv(r"C:\Users\danie\Downloads\countries of the world.csv")

In [8]:
df = pd.read_table(r"C:\Users\danie\Downloads\countries of the world.txt")

In [10]:
df = pd.read_json(r"C:\Users\danie\Downloads\json_sample.json")

In [12]:
df = pd.read_excel(r"C:\Users\danie\Downloads\world_population_excel_workbook.xlsx")
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [13]:
print(df.isnull().sum())

Rank                           0
CCA3                           0
Country                        0
Capital                        0
Continent                      0
2022 Population                0
2020 Population                0
2015 Population                0
2010 Population                0
2000 Population                0
1990 Population                0
1980 Population                0
1970 Population                0
Area (kmÂ²)                    0
Density (per kmÂ²)             0
Growth Rate                    0
World Population Percentage    0
dtype: int64

In [15]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [36]:
#Countries in Africa
africa = df[df["Continent"] == "Africa"]
africa.head(10)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
5,42,AGO,Angola,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
21,77,BEN,Benin,Porto-Novo,Africa,13352864,12643123,10932783,9445710,6998023,5133419,3833939,3023443,112622,118.5635,1.0274,0.17
26,144,BWA,Botswana,Gaborone,Africa,2630296,2546402,2305171,2091664,1726985,1341474,938578,592244,582000,4.5194,1.0162,0.03
31,58,BFA,Burkina Faso,Ouagadougou,Africa,22673762,21522626,18718019,16116845,11882888,9131361,6932967,5611666,272967,83.0641,1.0259,0.28
32,78,BDI,Burundi,Bujumbura,Africa,12889576,12220227,10727148,9126605,6307659,5483793,4312834,3497834,27834,463.0874,1.0270,0.16
34,53,CMR,Cameroon,Yaounde,Africa,27914536,26491087,23012646,19878036,15091594,11430520,8519891,6452787,475442,58.7128,1.0263,0.35
36,171,CPV,Cape Verde,Praia,Africa,593149,582640,552166,521212,458251,364563,317234,287262,4033,147.0739,1.0089,0.01
38,117,CAF,Central African Republic,Bangui,Africa,5579144,5343020,4819333,4660067,3759170,2809221,2415276,2067356,622984,8.9555,1.0224,0.07
39,69,TCD,Chad,N'Djamena,Africa,17723315,16644701,14140274,11894727,8259137,5827069,4408230,3667394,1284000,13.8032,1.0316,0.22

In [26]:
#Countries with population > 100M in 2022
large_population = df[df["2022 Population"] > 100000000]
large_population[["Country", "2022 Population"]]

           Country  2022 Population
16      Bangladesh        171186372
27          Brazil        215313498
41           China       1425887337
57           Egypt        110990103
63        Ethiopia        123379924
92           India       1417173173
93       Indonesia        275501339
102          Japan        123951692
131         Mexico        127504125
149        Nigeria        218541212
156       Pakistan        235824862
163    Philippines        115559009
171         Russia        144713314
221  United States        338289857

In [38]:
#Countries with growth rate above 1.02
high_growth = df[df["Growth Rate"] > 1.02]
high_growth[["Country", "Growth Rate"]]

                      Country  Growth Rate
0                 Afghanistan       1.0257
5                      Angola       1.0315
21                      Benin       1.0274
31               Burkina Faso       1.0259
32                    Burundi       1.0270
34                   Cameroon       1.0263
38   Central African Republic       1.0224
39                       Chad       1.0316
55                   DR Congo       1.0325
59          Equatorial Guinea       1.0247
63                   Ethiopia       1.0257
69              French Guiana       1.0239
71                      Gabon       1.0204
72                     Gambia       1.0250
84                     Guinea       1.0242
85              Guinea-Bissau       1.0218
90                    Hungary       1.0265
95                       Iraq       1.0221
100               Ivory Coast       1.0248
114                   Liberia       1.0210
120                Madagascar       1.0241
121                    Malawi       1.0259
124                      Mali       1.0314
128                Mauritania       1.0263
130                   Mayotte       1.0319
133                   Moldova       1.0691
139                Mozambique       1.0278
148                     Niger       1.0378
149                   Nigeria       1.0241
158                 Palestine       1.0227
164                    Poland       1.0404
168     Republic of the Congo       1.0231
172                    Rwanda       1.0234
183                   Senegal       1.0261
186              Sierra Leone       1.0220
189                  Slovakia       1.0359
191           Solomon Islands       1.0232
192                   Somalia       1.0312
198                     Sudan       1.0267
202                     Syria       1.0376
204                Tajikistan       1.0208
205                  Tanzania       1.0300
208                      Togo       1.0236
217                    Uganda       1.0304
225                   Vanuatu       1.0238
231                     Yemen       1.0217
232                    Zambia       1.0280
233                  Zimbabwe       1.0204

In [39]:
#Number of countries per continent
countries_per_continent = df.groupby("Continent")["Country"].count()
countries_per_continent

Continent
Africa           57
Asia             50
Europe           50
North America    40
Oceania          23
South America    14
Name: Country, dtype: int64

In [40]:
#Average population by continent 2022
avg_population = df.groupby("Continent")["2022 Population"].mean()
avg_population

Continent
Africa           2.503037e+07
Asia             9.442767e+07
Europe           1.486295e+07
North America    1.500740e+07
Oceania          1.958198e+06
South America    3.120119e+07
Name: 2022 Population, dtype: float64

In [45]:
#Top 5 countries 
top5 = df.sort_values(by="2022 Population", ascending=False)
top5[["Country", "2022 Population"]].head()

           Country  2022 Population
41           China       1425887337
92           India       1417173173
221  United States        338289857
93       Indonesia        275501339
156       Pakistan        235824862

In [42]:
summary = df.groupby("Continent")["2022 Population"].agg(
    ["count", "sum", "mean", "max", "min"]
)
summary

               count         sum          mean         max     min
Continent
Africa            57  1426730932  2.503037e+07   218541212  107118
Asia              50  4721383274  9.442767e+07  1425887337  449002
Europe            50   743147538  1.486295e+07   144713314     510
North America     40   600296136  1.500740e+07   338289857    4390
Oceania           23    45038554  1.958198e+06    26177413    1871
South America     14   436816608  3.120119e+07   215313498    3780